### ISSUE TITLE
final_data0.csv

### ISSUE THREAD

**Issue by hnuwxw** [tjzxh/HRC-LSTM#1]
Hi,
How do I get this file?

**Comment by tjzxh** [comment]
In fact，the file of 'final_data0.csv' is extracted from NGSIM dataset, you may know it if you read the publication. And if you want it for research, you can leave your email address here.

**Comment by hnuwxw** [comment]
I want to use this data set to do research on data analysis. My email is wxwhnuvy@gmail.com.
Thank you very much！

**Comment by tjzxh** [comment]
Already send now

**Comment by Gengmaosi** [comment]
Hi, I am a student from Zhejiang University and I want to use your data to do my graduation project research. May you send your data file? My email is gengmaosi@qq.com.
Thank you very much.

**Comment by tjzxh** [comment]
The data now can be obtained as below.
link：https://pan.baidu.com/s/143FJu_pEas__XzGnvkNdMA 
password：2333

**Comment by Gengmaosi** [comment]
Thank you very much!
